wandb_version: 1

lr:
  desc: null
  value: 0.0001
model_type:
  desc: null
  value: scratch
optimizer:
  desc: null
  value: SGD
criterion:
  desc: null
  value: ce
scheduler_patience:
  desc: null
  value: 3
scheduler_thresh:
  desc: null
  value: 0.001
num_epochs:
  desc: null
  value: 30
gpu_id:
  desc: null
  value: 0
wandb_run_name:
  desc: null
  value: Kyrylo-2-RMS
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685178836.579635
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.8.10
      5: 0.15.3
      8:
      - 1
      - 5
